apiVersion: v1
kind: Namespace
metadata:
  name: opentech-webapp
  labels:
    name: opentech-webapp
    security.compliance/pod-security-standard: restricted
---
apiVersion: v1
kind: LimitRange
metadata:
  name: webapp-limits
  namespace: opentech-webapp
spec:
  limits:
  - default:
      cpu: "500m"
      memory: "512Mi"
    defaultRequest:
      cpu: "250m"
      memory: "256Mi"
    type: Container
---
apiVersion: v1
kind: ResourceQuota
metadata:
  name: webapp-quota
  namespace: opentech-webapp
spec:
  hard:
    requests.cpu: "2"
    requests.memory: "4Gi"
    limits.cpu: "4"
    limits.memory: "8Gi"
    persistentvolumeclaims: "2"
    pods: "10"
    services: "5"