apiVersion: v1
kind: ServiceAccount
metadata:
  name: opentech-webapp
  namespace: opentech-webapp
  labels:
    app: opentech-webapp
automountServiceAccountToken: false
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  namespace: opentech-webapp
  name: opentech-webapp-role
rules:
- apiGroups: [""]
  resources: ["pods"]
  verbs: ["get", "list"]
- apiGroups: [""]
  resources: ["configmaps"]
  verbs: ["get", "list"]
- apiGroups: [""]
  resources: ["secrets"]
  verbs: ["get", "list"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: opentech-webapp-rolebinding
  namespace: opentech-webapp
subjects:
- kind: ServiceAccount
  name: opentech-webapp
  namespace: opentech-webapp
roleRef:
  kind: Role
  name: opentech-webapp-role
  apiGroup: rbac.authorization.k8s.io