apiVersion: v1
kind: Secret
metadata:
  name: supabase-secrets
  namespace: opentech-webapp
  labels:
    app: opentech-webapp
type: Opaque
stringData:
  url: "https://igkiffajkpfwdfxwokwg.supabase.co"
  anon-key: "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Imlna2lmZmFqa3Bmd2RmeHdva3dnIiwicm9sZSI6ImFub24iLCJpYXQiOjE3MzM3NTU4MzAsImV4cCI6MjA0OTMzMTgzMH0.k41hYubjGJvzwcBT9fAg0jYljd2OR7spM1msxtQ9tZM"
---
# For production, use external secret management:
# kubectl create secret generic supabase-secrets \
#   --from-literal=url="YOUR_SUPABASE_URL" \
#   --from-literal=anon-key="YOUR_SUPABASE_ANON_KEY" \
#   --namespace=opentech-webapp