import { Share2 } from "lucide-react";
import { Button } from "@/components/ui/button";
import { useToast } from "@/hooks/use-toast";

interface ImageHeaderProps {
  creator: {
    name: string;
    avatar: string;
  };
  timeAgo: string;
  imageUrl?: string;
  imageId?: number;
}

export const ImageHeader = ({ creator, timeAgo, imageUrl, imageId }: ImageHeaderProps) => {
  const { toast } = useToast();

  const handleShare = async () => {
    if (!imageUrl || !imageId) {
      toast({
        title: "Error",
        description: "No image available to share",
        variant: "destructive",
      });
      return;
    }

    try {
      // Create share data with image details
      const shareData = {
        title: `Generated by ${creator.name}`,
        text: `Check out this amazing AI-generated image!`,
        url: imageUrl,
      };

      // Try native sharing first
      if (navigator.canShare && navigator.canShare(shareData)) {
        await navigator.share(shareData);
        toast({
          title: "Success",
          description: "Image shared successfully!",
        });
      } else {
        // Fallback to clipboard
        const shareableUrl = `${window.location.origin}/marketplace?image=${imageId}`;
        await navigator.clipboard.writeText(shareableUrl);
        toast({
          title: "Success",
          description: "Image link copied to clipboard!",
        });
      }
    } catch (error) {
      if (error instanceof Error && error.name === 'AbortError') {
        // User cancelled sharing - no need for error message
        return;
      }
      console.error('Share error:', error);
      toast({
        title: "Error",
        description: "Unable to share image. Please try again.",
        variant: "destructive",
      });
    }
  };

  return (
    <div className="flex items-center justify-between mb-2">
      <div className="flex items-center space-x-2">
        <img
          src={creator.avatar}
          alt={creator.name}
          className="w-6 h-6 rounded-full"
        />
        <span className="text-sm font-medium">{creator.name}</span>
        <span className="text-sm text-gray-400">{timeAgo}</span>
      </div>
      <Button 
        variant="ghost" 
        size="sm" 
        className="p-1 hover:bg-gray-100 dark:hover:bg-gray-800 transition-colors"
        onClick={handleShare}
      >
        <Share2 className="h-4 w-4" />
      </Button>
    </div>
  );
};