import { Share2 } from "lucide-react";
import { Button } from "@/components/ui/button";
import { useToast } from "@/hooks/use-toast";

interface ShareButtonProps {
  creator: {
    name: string;
  };
  imageUrl?: string;
  imageId?: number;
}

export const ShareButton = ({ creator, imageUrl, imageId }: ShareButtonProps) => {
  const { toast } = useToast();

  const handleShare = async () => {
    if (!imageUrl || !imageId) {
      toast({
        title: "Error",
        description: "No image available to share",
        variant: "destructive",
      });
      return;
    }

    try {
      // Create a shareable URL that points to the marketplace with the image ID
      const shareableUrl = `${window.location.origin}/marketplace?image=${imageId}`;
      
      const shareData = {
        title: `Generated by ${creator.name}`,
        text: `Check out this amazing AI-generated image!`,
        url: shareableUrl,
      };

      if (navigator.canShare && navigator.canShare(shareData)) {
        await navigator.share(shareData);
        toast({
          title: "Success",
          description: "Image shared successfully!",
        });
      } else {
        await navigator.clipboard.writeText(shareableUrl);
        toast({
          title: "Success",
          description: "Image link copied to clipboard!",
        });
      }
    } catch (error) {
      if (error instanceof Error && error.name === 'AbortError') {
        return;
      }
      console.error('Share error:', error);
      toast({
        title: "Error",
        description: "Unable to share image. Please try again.",
        variant: "destructive",
      });
    }
  };

  return (
    <Button 
      variant="ghost" 
      size="sm" 
      className="p-1 hover:bg-gray-100 dark:hover:bg-gray-800 transition-colors"
      onClick={handleShare}
    >
      <Share2 className="h-4 w-4" />
    </Button>
  );
};