apiVersion: 1

datasources:
  - name: Prometheus
    type: prometheus
    access: proxy
    orgId: 1
    url: http://prometheus:9090
    basicAuth: false
    isDefault: true
    version: 1
    editable: true

  - name: InfluxDB
    type: influxdb
    access: proxy
    orgId: 1
    url: http://influxdb:8086
    database: analytics
    user: admin
    secureJsonData:
      password: opentech2024
    version: 1
    editable: true

  - name: Elasticsearch
    type: elasticsearch
    access: proxy
    orgId: 1
    url: http://elasticsearch:9200
    database: "[logs-]YYYY.MM.DD"
    interval: Daily
    timeField: "@timestamp"
    version: 1
    editable: true