-- First, add the missing provider column to generated_images if it doesn't exist
ALTER TABLE generated_images ADD COLUMN IF NOT EXISTS provider text DEFAULT 'openai';

-- Add provider version and generation settings columns
ALTER TABLE generated_images ADD COLUMN IF NOT EXISTS provider_version text;
ALTER TABLE generated_images ADD COLUMN IF NOT EXISTS generation_settings jsonb DEFAULT '{}'::jsonb;

-- Add video generations table for future video capability
CREATE TABLE IF NOT EXISTS video_generations (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_id uuid REFERENCES auth.users(id),
  prompt text NOT NULL,
  video_url text,
  thumbnail_url text,
  duration_seconds integer,
  status text DEFAULT 'pending',
  provider text DEFAULT 'xai',
  provider_version text,
  generation_settings jsonb DEFAULT '{}'::jsonb,
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now()
);

-- Enable RLS on video_generations
ALTER TABLE video_generations ENABLE ROW LEVEL SECURITY;

-- Create RLS policies for video_generations
CREATE POLICY "Users can view their own video generations" 
ON video_generations FOR SELECT 
USING (auth.uid() = user_id);

CREATE POLICY "Users can insert their own video generations" 
ON video_generations FOR INSERT 
WITH CHECK (auth.uid() = user_id);

CREATE POLICY "Users can update their own video generations" 
ON video_generations FOR UPDATE 
USING (auth.uid() = user_id);

-- Add provider performance metrics table
CREATE TABLE IF NOT EXISTS provider_metrics (
  id uuid DEFAULT gen_random_uuid() PRIMARY KEY,
  provider text NOT NULL,
  provider_version text,
  metric_type text NOT NULL, -- 'generation_time', 'success_rate', 'quality_score', 'cost'
  metric_value numeric NOT NULL,
  recorded_at timestamp with time zone DEFAULT now(),
  metadata jsonb DEFAULT '{}'::jsonb
);

-- Enable RLS on provider_metrics (admin only)
ALTER TABLE provider_metrics ENABLE ROW LEVEL SECURITY;

CREATE POLICY "Admins can manage provider metrics" 
ON provider_metrics FOR ALL 
USING (is_admin_user());

-- Add indexes for performance
CREATE INDEX IF NOT EXISTS idx_generated_images_provider_version ON generated_images(provider, provider_version);
CREATE INDEX IF NOT EXISTS idx_video_generations_user_status ON video_generations(user_id, status);
CREATE INDEX IF NOT EXISTS idx_provider_metrics_provider_type ON provider_metrics(provider, metric_type);
CREATE INDEX IF NOT EXISTS idx_provider_metrics_recorded_at ON provider_metrics(recorded_at);